/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PostSlugRouteImport } from "./routes/post/$slug";
import { Route as PostIndexRouteImport } from "./routes/post/index";
import { Route as PracticeGomokuRouteImport } from "./routes/practice/gomoku";
import { Route as PracticeIndexRouteImport } from "./routes/practice/index";
import { Route as ReleaseRouteImport } from "./routes/release";

const ReleaseRoute = ReleaseRouteImport.update({
  id: "/release",
  path: "/release",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: "/practice/",
  path: "/practice/",
  getParentRoute: () => rootRouteImport,
} as any);
const PostIndexRoute = PostIndexRouteImport.update({
  id: "/post/",
  path: "/post/",
  getParentRoute: () => rootRouteImport,
} as any);
const PracticeGomokuRoute = PracticeGomokuRouteImport.update({
  id: "/practice/gomoku",
  path: "/practice/gomoku",
  getParentRoute: () => rootRouteImport,
} as any);
const PostSlugRoute = PostSlugRouteImport.update({
  id: "/post/$slug",
  path: "/post/$slug",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/release": typeof ReleaseRoute;
  "/post/$slug": typeof PostSlugRoute;
  "/practice/gomoku": typeof PracticeGomokuRoute;
  "/post/": typeof PostIndexRoute;
  "/practice/": typeof PracticeIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/release": typeof ReleaseRoute;
  "/post/$slug": typeof PostSlugRoute;
  "/practice/gomoku": typeof PracticeGomokuRoute;
  "/post": typeof PostIndexRoute;
  "/practice": typeof PracticeIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/release": typeof ReleaseRoute;
  "/post/$slug": typeof PostSlugRoute;
  "/practice/gomoku": typeof PracticeGomokuRoute;
  "/post/": typeof PostIndexRoute;
  "/practice/": typeof PracticeIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about" | "/release" | "/post/$slug" | "/practice/gomoku" | "/post/" | "/practice/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/release" | "/post/$slug" | "/practice/gomoku" | "/post" | "/practice";
  id: "__root__" | "/" | "/about" | "/release" | "/post/$slug" | "/practice/gomoku" | "/post/" | "/practice/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  ReleaseRoute: typeof ReleaseRoute;
  PostSlugRoute: typeof PostSlugRoute;
  PracticeGomokuRoute: typeof PracticeGomokuRoute;
  PostIndexRoute: typeof PostIndexRoute;
  PracticeIndexRoute: typeof PracticeIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/release": {
      id: "/release";
      path: "/release";
      fullPath: "/release";
      preLoaderRoute: typeof ReleaseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/practice/": {
      id: "/practice/";
      path: "/practice";
      fullPath: "/practice/";
      preLoaderRoute: typeof PracticeIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/post/": {
      id: "/post/";
      path: "/post";
      fullPath: "/post/";
      preLoaderRoute: typeof PostIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/practice/gomoku": {
      id: "/practice/gomoku";
      path: "/practice/gomoku";
      fullPath: "/practice/gomoku";
      preLoaderRoute: typeof PracticeGomokuRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/post/$slug": {
      id: "/post/$slug";
      path: "/post/$slug";
      fullPath: "/post/$slug";
      preLoaderRoute: typeof PostSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReleaseRoute: ReleaseRoute,
  PostSlugRoute: PostSlugRoute,
  PracticeGomokuRoute: PracticeGomokuRoute,
  PostIndexRoute: PostIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
